### ISSUE TITLE
What's the proper way to matrix list_arguments

### ISSUE THREAD

**Issue by wimo7083** [codefresh-io/docs.codefresh.io#132]
This is a fairly contrived example but this type of matrix but matrix variants are very common when having to support multiple versions. 

```
version: '1.0'
steps:
  BuildVariants:    
    image_name: java_variant
    type: build
    dockerfile: Dockerfile.variants
    matrix:      
      build_arguments:
        - [JDK_VERSION=7]
        - [JDK_VERSION=8]
        - [JDK_VERSION=9]
      build_arguments:
        - [MAVEN_VERSION=1]
        - [MAVEN_VERSION=2]
```

```Dockerfile
FROM alpine
ARG JDK_VERSION
ARG MAVEN_VERSION
RUN echo "${JDK_VERSION} {MAVEN_VERSION}"
```

Unless I'm missing something the above doesn't appear to be possible unless I do something involve multiple steps. 

If I have the same build step parrallelized I can use the same "${{BuildVariants}}" reference to run against the same later steps up to and including the publish.

**Comment by ajshock** [comment]
It seems the implicit mapping is from `build_arguments:` plural into the Docker command line allowing for singular `--buil-arg` instances.  As such, by using `build_arguments` (plural) as the yaml key under `matrix:`, there's no way to direct permute combinations of multiple `--build-arg` key/values into said Dockerfile.  
 
The only way I saw the UI allowing the above combinations of JDK_VERSION and MAVEN_VERSION was to manually permute the arguments into a list like:
```yaml
matrix:
    build_arguments:  
        - [JDK_VERSION=7, MAVEN_VERSION=1]
        - [JDK_VERSION=7, MAVEN_VERSION=2]
        - [JDK_VERSION=8, MAVEN_VERSION=1]
        - [JDK_VERSION=8, MAVEN_VERSION=2]
        - [JDK_VERSION=9, MAVEN_VERSION=1]
        - [JDK_VERSION=9, MAVEN_VERSION=2]
```
but that defeats the value of using the `matrix:` logic in the first place
